[build]
  builder = "NIXPACKS"
  buildCommand = "cd server && npm install"
  startCommand = "cd server && node server.js"

[deploy]
  numReplicas = 1
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10